name: Setup Cache
description: "Setup Rust artifact caching"
inputs:
  cache-key:
    description: "Caching key used for invalidation and uploading"
    required: true
  cache-update:
    description: "Whether to overwrite existing caches"

runs:
  using: "composite"

  steps:
    - name: Setup sccache
      uses: hanabi1224/sccache-action@v1.2.0 # https://github.com/hanabi1224/sccache-action used by Forest.
      with:
        release-name: v0.3.1
        # Caching everything separately, in case they don't ask for the same things to be compiled.
        cache-key: ${{ inputs.cache-key }}
        # Not sure why we should ever update a cache that has the hash of the lock file in it.
        # In Forest it only contains the rust-toolchain, so it makes sense to update because dependencies could have changed.
        cache-update: ${{ inputs.cache-update }}
