#!/usr/bin/env bash
# Generated from topologies/example.yaml
set -e
# Create the agent(s)
make --no-print-directory agent/up IPC_AGENT_NR=0
make --no-print-directory agent/up IPC_AGENT_NR=1
# Create the root node(s)
make --no-print-directory node/up IPC_NODE_NR=0 IPC_AGENT_NR=0 IPC_SUBNET_NAME=vertebrates
# Alternate connecting agents and creating subnets and nodes to run them
make --no-print-directory connect IPC_NODE_NR=0 IPC_AGENT_NR=0
make --no-print-directory node/up IPC_NODE_NR=1 IPC_AGENT_NR=1 IPC_PARENT_NODE_NR=0 IPC_PARENT_AGENT_NR=0 IPC_WALLET_NR=0 IPC_SUBNET_NAME=warm-blooded IPC_WALLET_FUNDS=100 IPC_SUBNET_FUNDS=90 IPC_COLLATERAL=1 IPC_MIN_VALIDATOR_STAKE=1 IPC_MIN_VALIDATORS=0 IPC_BOTTOMUP_CHECK_PERIOD=10 IPC_TOPDOWN_CHECK_PERIOD=10
make --no-print-directory node/up IPC_NODE_NR=2 IPC_AGENT_NR= IPC_PARENT_NODE_NR=0 IPC_PARENT_AGENT_NR=0 IPC_WALLET_NR=1 IPC_SUBNET_NAME=cold-blooded IPC_WALLET_FUNDS=100 IPC_SUBNET_FUNDS=90 IPC_COLLATERAL=1 IPC_MIN_VALIDATOR_STAKE=1 IPC_MIN_VALIDATORS=0 IPC_BOTTOMUP_CHECK_PERIOD=10 IPC_TOPDOWN_CHECK_PERIOD=10
make --no-print-directory node/up IPC_NODE_NR=5 IPC_AGENT_NR=0 IPC_PARENT_NODE_NR=0 IPC_PARENT_AGENT_NR=0 IPC_WALLET_NR=1 IPC_SUBNET_NAME=warm-blooded IPC_WALLET_FUNDS=50 IPC_SUBNET_FUNDS=40 IPC_COLLATERAL=2 IPC_MIN_VALIDATOR_STAKE=1 IPC_MIN_VALIDATORS=0 IPC_BOTTOMUP_CHECK_PERIOD=10 IPC_TOPDOWN_CHECK_PERIOD=10
make --no-print-directory connect IPC_NODE_NR=1 IPC_AGENT_NR=1
make --no-print-directory node/up IPC_NODE_NR=3 IPC_AGENT_NR= IPC_PARENT_NODE_NR=1 IPC_PARENT_AGENT_NR=1 IPC_WALLET_NR=0 IPC_SUBNET_NAME=mammals IPC_WALLET_FUNDS=10 IPC_SUBNET_FUNDS=6 IPC_COLLATERAL=1 IPC_MIN_VALIDATOR_STAKE=1 IPC_MIN_VALIDATORS=0 IPC_BOTTOMUP_CHECK_PERIOD=10 IPC_TOPDOWN_CHECK_PERIOD=10
make --no-print-directory node/up IPC_NODE_NR=4 IPC_AGENT_NR= IPC_PARENT_NODE_NR=1 IPC_PARENT_AGENT_NR=1 IPC_WALLET_NR=1 IPC_SUBNET_NAME=birds IPC_WALLET_FUNDS=10 IPC_SUBNET_FUNDS=7 IPC_COLLATERAL=1 IPC_MIN_VALIDATOR_STAKE=1 IPC_MIN_VALIDATORS=0 IPC_BOTTOMUP_CHECK_PERIOD=10 IPC_TOPDOWN_CHECK_PERIOD=10
make --no-print-directory connect IPC_NODE_NR=5 IPC_AGENT_NR=0
