#--network ${NETWORK_NAME} \
#--publish ${ANVIL_HOST_PORT}:8545 \
[tasks.anvil-run]
script = """
docker run \
  ${FLAGS} \
  --name ${ANVIL_CONTAINER_NAME} \
  --network ${NETWORK_NAME} \
  --publish ${ANVIL_HOST_PORT}:8545 \
  ${FOUNDRY_DOCKER_IMAGE} "anvil --host 0.0.0.0"
"""
dependencies = ["docker-network-create"]

[tasks.anvil-start]
extend = "anvil-run"
env = { "FLAGS" = "-d" }

[tasks.anvil-restart]
extend = "anvil-run"
env = { "FLAGS" = "-d" }
dependencies = ["anvil-destroy"]

[tasks.anvil-stop]
env = { "CONTAINER_NAME" = "${ANVIL_CONTAINER_NAME}" }
run_task = "docker-stop"

[tasks.anvil-destroy]
env = { "CONTAINER_NAME" = "${ANVIL_CONTAINER_NAME}" }
run_task = "docker-destroy"
