
[tasks.loki-run]
script = """
docker run \
  ${FLAGS} \
  --name ${LOKI_CONTAINER_NAME} \
  --net host \
  -v ${LOKI_CONFIG_FOLDER}:/mnt/config \
  ${LOKI_DOCKER_IMAGE} -config.file=/mnt/config/loki-config.yaml
"""

[tasks.loki-start]
extend = "loki-run"
env = { "FLAGS" = "-d" }

[tasks.loki-restart]
extend = "loki-run"
env = { "FLAGS" = "-d" }
dependencies = ["loki-destroy"]

[tasks.loki-stop]
env = { "CONTAINER_NAME" = "${LOKI_CONTAINER_NAME}" }
run_task = "docker-stop"

[tasks.loki-destroy]
env = { "CONTAINER_NAME" = "${LOKI_CONTAINER_NAME}" }
run_task = "docker-destroy"

[tasks.loki-logs]
extend = "docker-logs"
env = { "CONTAINER_NAME" = "${LOKI_CONTAINER_NAME}" }
