[tasks.objects-run]
script = """
docker run \
  ${FLAGS} \
  --name ${OBJECTS_CONTAINER_NAME} \
  --init \
  --user $(id -u) \
  --network ${NETWORK_NAME} \
  --volume ${BASE_DIR}:/data \
  --publish ${OBJECTS_HOST_PORT}:8001 \
  --env FM_CHAIN_NAME=${SUBNET_ID} \
  --env FM_TRACING__CONSOLE__LEVEL=${OBJECTS_LOG_LEVEL} \
  --env TENDERMINT_RPC_URL=http://${CMT_CONTAINER_NAME}:26657 \
  --env IROH_RPC_ADDR=${IROH_CONTAINER_NAME}:4919 \
  --env RUST_BACKTRACE=1 \
  ${FM_DOCKER_IMAGE} \
  --network=${FM_NETWORK} \
  ${CMD}
"""
dependencies = ["docker-network-create"]

[tasks.objects-start]
extend = "objects-run"
env = { "CMD" = "objects run", "FLAGS" = "-d" }

[tasks.objects-stop]
env = { "CONTAINER_NAME" = "${OBJECTS_CONTAINER_NAME}" }
run_task = "docker-stop"

[tasks.objects-destroy]
env = { "CONTAINER_NAME" = "${OBJECTS_CONTAINER_NAME}" }
run_task = "docker-destroy"

[tasks.objects-logs]
extend = "docker-logs"
env = { "CONTAINER_NAME" = "${OBJECTS_CONTAINER_NAME}" }
