[tasks.prometheus-run]
script = """
# TODO: need to add a --user $(id -u):(65534?)  once we figure out what group:user has the needed permission
docker run \
  ${FLAGS} \
  --name ${PROMETHEUS_CONTAINER_NAME} \
  --init \
  --network ${NETWORK_NAME} \
  --volume ${PROMETHEUS_DIR}:/data/prometheus \
  --volume ${PROMETHEUS_CONFIG_FOLDER}/prometheus.yaml:/etc/prometheus/prometheus.yaml \
  --publish ${PROMETHEUS_HOST_PORT}:9090 \
  ${PROMETHEUS_DOCKER_IMAGE}
"""
dependencies = ["docker-network-create"]

[tasks.prometheus-start]
extend = "prometheus-run"
env = { "FLAGS" = "-d" }

[tasks.prometheus-stop]
env = { "CONTAINER_NAME" = "${PROMETHEUS_CONTAINER_NAME}" }
run_task = "docker-stop"

[tasks.prometheus-destroy]
env = { "CONTAINER_NAME" = "${PROMETHEUS_CONTAINER_NAME}" }
run_task = "docker-destroy"

[tasks.prometheus-logs]
extend = "docker-logs"
env = { "CONTAINER_NAME" = "${PROMETHEUS_CONTAINER_NAME}" }
