[tasks.prometheus-run]
script = """
mkdir -p $PROMETHEUS_DIR
docker run \
  ${FLAGS} \
  --name ${PROMETHEUS_CONTAINER_NAME} \
  --init \
  --user $(id -u) \
  --network ${NETWORK_NAME} \
  --publish 127.0.0.1:${PROMETHEUS_HOST_PORT}:9090 \
  --volume ${PROMETHEUS_DIR}:/prometheus \
  --volume ${PROMETHEUS_CONFIG_FOLDER}/prometheus.yaml:/etc/prometheus/prometheus.yml \
  ${PROMETHEUS_DOCKER_IMAGE}
"""

[tasks.prometheus-start]
extend = "prometheus-run"
env = { "FLAGS" = "-d" }

[tasks.prometheus-restart]
extend = "prometheus-run"
env = { "FLAGS" = "-d" }
dependencies = ["prometheus-destroy"]

[tasks.prometheus-stop]
env = { "CONTAINER_NAME" = "${PROMETHEUS_CONTAINER_NAME}" }
run_task = "docker-stop"

[tasks.prometheus-destroy]
env = { "CONTAINER_NAME" = "${PROMETHEUS_CONTAINER_NAME}" }
run_task = "docker-destroy"

[tasks.prometheus-logs]
extend = "docker-logs"
env = { "CONTAINER_NAME" = "${PROMETHEUS_CONTAINER_NAME}" }
