[tasks.create-log-volume]
script = "docker volume create fendermint-logs"

[tasks.destroy-log-volume]
# removing the volume will return exit code 1 if it does not exist, which we can just ignore
script = "docker volume rm fendermint-logs || true"


[tasks.promtail-run]
script = """
unixtime=$(date +%s)
echo "Starting promtail with promtailrunid: $unixtime"
docker run \
  --name ${PROMTAIL_CONTAINER_NAME} \
  --network ${SUBNET_ID} \
  --port 9080:${PROMTAIL_AGENT_PORT} \
  --volume /var/run/docker.sock:/var/run/docker.sock
  --volume "$(readlink -f ../../../infra/promtail)/promtail-config.yaml:/etc/promtail/promtail-config.yaml" \
  --volume ${FM_DIR}/data/logs:/var/log/findermint/   grafana/promtail:3.0.0 -config.file=/etc/promtail/promtail-config.yaml
"""

[tasks.promtail-start]
extend = "promtail-run"
env = { "FLAGS" = "-d" }

[tasks.promtail-destroy]
env = { "CONTAINER_NAME" = "${PROMTAIL_CONTAINER_NAME}" }
run_task = "docker-destroy"

[tasks.promtail-logs]
extend = "docker-logs"
env = { "CONTAINER_NAME" = "${PROMTAIL_CONTAINER_NAME}" }
