[tasks.create-log-volume]
script = "docker volume create fendermint-logs"

[tasks.destroy-log-volume]
# removing the volume will return exit code 1 if it does not exist, which we can just ignore
script = "docker volume rm fendermint-logs || true"

[tasks.promtail-run]
script = """
docker run \
  ${FLAGS} \
  --name ${PROMTAIL_CONTAINER_NAME} \
  --network ${NETWORK_NAME} \
  --publish 127.0.0.1:${PROMTAIL_AGENT_HOST_PORT}:9080 \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  --volume ${PROMTAIL_CONFIG_FOLDER}/promtail-config.yaml:/etc/promtail/promtail-config.yaml \
  --volume ${FM_DIR}/data/logs:/var/log/fendermint/ \
  ${PROMTAIL_DOCKER_IMAGE} \
  --client.external-labels=host=$(hostname),node=$NODE_NAME \
  --config.file=/etc/promtail/promtail-config.yaml \
  --client.url=http://loki:3100/loki/api/v1/push
"""

[tasks.promtail-start]
extend = "promtail-run"
env = { "FLAGS" = "-d" }

[tasks.promtail-destroy]
env = { "CONTAINER_NAME" = "${PROMTAIL_CONTAINER_NAME}" }
run_task = "docker-destroy"

[tasks.promtail-logs]
extend = "docker-logs"
env = { "CONTAINER_NAME" = "${PROMTAIL_CONTAINER_NAME}" }
