[package]
name = "fendermint_actor_objectstore"
description = "Actor for object storage"
license.workspace = true
edition.workspace = true
authors.workspace = true
version = "0.1.0"

[lib]
## lib is necessary for integration tests
## cdylib is necessary for Wasm build
crate-type = ["cdylib", "lib"]

[dependencies]
anyhow = { workspace = true }
cid = { workspace = true, default-features = false }
fil_actors_runtime = { workspace = true }
frc42_dispatch = { workspace = true }
log = { workspace = true, features = ["std"] }
num-derive = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_tuple = { workspace = true }
fvm_ipld_blockstore = { workspace = true }
fvm_ipld_encoding = { workspace = true }
fvm_ipld_hamt = { workspace = true }
fvm_shared = { workspace = true }

fendermint_actor_machine = { path = "../machine" }

[dev-dependencies]
fendermint_testing = { path = "../../testing", features = ["arb"] }
fil_actors_runtime = { workspace = true, features = [
    "test_utils",
] }
quickcheck = { workspace = true }
quickcheck_macros = { workspace = true }

[features]
fil-actor = ["fil_actors_runtime/fil-actor"]
