[package]
name = "build-rs-utils"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
license-file.workspace = true

[dependencies]
owo-colors = "4"
build-print = "0.1.1"
