[package]
name = "build-rs-utils"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
owo-colors = "4"
color-eyre = "0.6"
tokio = { version = "1", features = ["rt"] }
