[package]
name = "objectstore_syscall"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
ambassador = { workspace = true }
anyhow = { workspace = true }
cid = { workspace = true }
fvm = { workspace = true }
fvm_shared = { workspace = true }
fvm_ipld_blockstore = { workspace = true }
num-traits = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
ipfs-api-backend-hyper = { version = "0.6.0", features = ["with-send-sync"] }
