[package]
name = "objectstore_syscall"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ambassador = { workspace = true }
anyhow = { workspace = true }
cid = { workspace = true }
fvm = { workspace = true }
fvm_shared = { workspace = true }
fvm_ipld_blockstore = { workspace = true }
num-traits = { workspace = true }
fvm_ipld_car = { workspace = true }
multihash = { workspace = true }
rand = "0.8.5"
async-std = "1.12.0"
