[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
fs_permissions = [{ access = "read-write", path = "./config.json"}]
remappings = [
    "@ipc/=node_modules/@consensus-shipyard/ipc-contracts/",
    ## this murky remapping is only needed transitively for testing; we should try to get rid of this.
    "murky/=node_modules/@consensus-shipyard/ipc-contracts/lib/murky/src/",
]
