[package]
name = "hoku_syscalls"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
fvm = { workspace = true }
fvm_shared = { workspace = true }
iroh = { workspace = true }
once_cell = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

hoku_kernel_ops = { path = "../kernel/ops" }
iroh_manager = { path = "../iroh_manager" }
