[accounts.AQ-]

[accounts.YAT]

[accounts.__AIik_j]

[rootnet]
type = "New"
ipc_contracts_owner = "__AIik_j"

[rootnet.validators]
AQ- = "3199669152641157384"
YAT = "4725570830599158438"

[rootnet.balances]
AQ- = "100000000000000000000"
YAT = "100000000000000000000"
__AIik_j = "100000000000000000000"

[rootnet.nodes.H-OQy]
ethapi = false
seed_nodes = ["v_i8Zob2"]

[rootnet.nodes.H-OQy.mode]
type = "Validator"
validator = "YAT"

[rootnet.nodes.v_i8Zob2]
ethapi = false
seed_nodes = []

[rootnet.nodes.v_i8Zob2.mode]
type = "Validator"
validator = "AQ-"

[rootnet.env]
CMT_BbFqXr = "莭~"
CMT_CVVs = ""
FM_94_UH__V = "”"
FM_9Uc_6 = "$񺔤 T:\t"

[subnets.LiP3Aa]
creator = "AQ-"

[subnets.LiP3Aa.validators]
AQ- = "3208789968795461243"
YAT = "4067256200506058538"

[subnets.LiP3Aa.balances]
YAT = "163461705830362489"

[subnets.LiP3Aa.nodes.KzA_y]
ethapi = true
seed_nodes = []
parent_node = "H-OQy"

[subnets.LiP3Aa.nodes.KzA_y.mode]
type = "Validator"
validator = "AQ-"

[subnets.LiP3Aa.nodes.bxD_]
ethapi = false
seed_nodes = ["KzA_y"]
parent_node = "H-OQy"

[subnets.LiP3Aa.nodes.bxD_.mode]
type = "Validator"
validator = "YAT"

[subnets.LiP3Aa.relayers.GBJee6I]
submitter = "__AIik_j"
follow_node = "bxD_"
submit_node = "H-OQy"

[subnets.LiP3Aa.relayers.V-YH5_]
submitter = "AQ-"
follow_node = "bxD_"
submit_node = "H-OQy"

[subnets.LiP3Aa.relayers._eRAVi]
submitter = "__AIik_j"
follow_node = "bxD_"
submit_node = "v_i8Zob2"

[subnets.LiP3Aa.bottom_up_checkpoint]
period = 14470

[subnets.LiP3Aa.env]
CMT_BGn = "$‑P"
FM_4KaVz = "~ᘰ잲ಕ/⁢"

[subnets.LiP3Aa.subnets.8YI__]
creator = "YAT"

[subnets.LiP3Aa.subnets.8YI__.validators]
AQ- = "7474117444708975073"
YAT = "704272210253566680"

[subnets.LiP3Aa.subnets.8YI__.balances]
__AIik_j = "4931498906063716101"

[subnets.LiP3Aa.subnets.8YI__.nodes.Pu0-1]
ethapi = true
seed_nodes = ["_VBAH"]
parent_node = "bxD_"

[subnets.LiP3Aa.subnets.8YI__.nodes.Pu0-1.mode]
type = "Full"

[subnets.LiP3Aa.subnets.8YI__.nodes._VBAH]
ethapi = true
seed_nodes = []
parent_node = "bxD_"

[subnets.LiP3Aa.subnets.8YI__.nodes._VBAH.mode]
type = "Validator"
validator = "AQ-"

[subnets.LiP3Aa.subnets.8YI__.relayers.Fn5]
submitter = "YAT"
follow_node = "Pu0-1"
submit_node = "bxD_"

[subnets.LiP3Aa.subnets.8YI__.bottom_up_checkpoint]
period = 2

[subnets.LiP3Aa.subnets.8YI__.env]
CMT_xKeJD8 = "¨\t[轻h~"

[subnets.LiP3Aa.subnets.BMcX]
creator = "YAT"

[subnets.LiP3Aa.subnets.BMcX.validators]
AQ- = "1"
__AIik_j = "4253330905707509191"

[subnets.LiP3Aa.subnets.BMcX.balances]
YAT = "7095226404222467058"
__AIik_j = "285822876018329041"

[subnets.LiP3Aa.subnets.BMcX.nodes.qKgTswA]
ethapi = true
seed_nodes = ["szuvBc"]
parent_node = "KzA_y"

[subnets.LiP3Aa.subnets.BMcX.nodes.qKgTswA.mode]
type = "Validator"
validator = "__AIik_j"

[subnets.LiP3Aa.subnets.BMcX.nodes.szuvBc]
ethapi = false
seed_nodes = []
parent_node = "bxD_"

[subnets.LiP3Aa.subnets.BMcX.nodes.szuvBc.mode]
type = "Validator"
validator = "AQ-"

[subnets.LiP3Aa.subnets.BMcX.relayers.EfBDlNr]
submitter = "YAT"
follow_node = "szuvBc"
submit_node = "KzA_y"

[subnets.LiP3Aa.subnets.BMcX.relayers.YXgj8]
submitter = "YAT"
follow_node = "szuvBc"
submit_node = "KzA_y"

[subnets.LiP3Aa.subnets.BMcX.relayers.qQN_l]
submitter = "YAT"
follow_node = "szuvBc"
submit_node = "bxD_"

[subnets.LiP3Aa.subnets.BMcX.bottom_up_checkpoint]
period = 78277

[subnets.U2R]
creator = "AQ-"

[subnets.U2R.validators]
YAT = "458065369041837599"
__AIik_j = "1"

[subnets.U2R.balances]
AQ- = "7929997960992083551"

[subnets.U2R.nodes.VwKz-]
ethapi = false
seed_nodes = ["vSqDgoA"]
parent_node = "H-OQy"

[subnets.U2R.nodes.VwKz-.mode]
type = "Full"

[subnets.U2R.nodes.vSqDgoA]
ethapi = true
seed_nodes = []
parent_node = "H-OQy"

[subnets.U2R.nodes.vSqDgoA.mode]
type = "Validator"
validator = "YAT"

[subnets.U2R.relayers.qzm69hNE]
submitter = "YAT"
follow_node = "VwKz-"
submit_node = "v_i8Zob2"

[subnets.U2R.bottom_up_checkpoint]
period = 25216
