[accounts.ELJZq4]

[accounts.TD-cbBcg]

[accounts.XQnNCy0Z]

[accounts._9B]

[accounts._L0_-p]

[deployment.New]
deployer = "XQnNCy0Z"

[subnets.6Ws]
creator = "ELJZq4"

[subnets.6Ws.validators]
XQnNCy0Z = "3044423974611235321"

[subnets.6Ws.balances]
ELJZq4 = "5490305012793048088"
TD-cbBcg = "2158424432298538959"
XQnNCy0Z = "6542703289484072143"

[subnets.6Ws.nodes.jTgTFS]
ethapi = true
seed_nodes = []

[subnets.6Ws.nodes.jTgTFS.mode]
Validator = "XQnNCy0Z"

[subnets.6Ws.relayers.zAEVfG8]
submitter = "TD-cbBcg"
follow_node = "jTgTFS"

[subnets.6Ws.subnets]

[subnets.T-iAulsf]
creator = "_L0_-p"

[subnets.T-iAulsf.validators]
TD-cbBcg = "8500541919079772039"
XQnNCy0Z = "285041714558338708"
_9B = "6470871941514909199"
_L0_-p = "6012780069222979283"

[subnets.T-iAulsf.balances]
ELJZq4 = "467060481459866379"
_L0_-p = "5321833421312707019"

[subnets.T-iAulsf.nodes.9d6]
ethapi = false
seed_nodes = ["jxMoQdMT", "R6Q"]

[subnets.T-iAulsf.nodes.9d6.mode]
Validator = "_L0_-p"

[subnets.T-iAulsf.nodes.R6Q]
ethapi = false
seed_nodes = ["jxMoQdMT"]

[subnets.T-iAulsf.nodes.R6Q.mode]
Validator = "_9B"

[subnets.T-iAulsf.nodes.g72w]
ethapi = true
seed_nodes = []

[subnets.T-iAulsf.nodes.g72w.mode]
Validator = "TD-cbBcg"

[subnets.T-iAulsf.nodes.jxMoQdMT]
ethapi = false
seed_nodes = ["g72w"]

[subnets.T-iAulsf.nodes.jxMoQdMT.mode]
Validator = "XQnNCy0Z"

[subnets.T-iAulsf.relayers.CwBie]
submitter = "XQnNCy0Z"
follow_node = "9d6"

[subnets.T-iAulsf.relayers.Zpe]
submitter = "_L0_-p"
follow_node = "9d6"

[subnets.T-iAulsf.subnets.B_C]
creator = "ELJZq4"

[subnets.T-iAulsf.subnets.B_C.validators]
ELJZq4 = "272927670009202172"
TD-cbBcg = "8237074886614116492"
_9B = "7259748219012866175"

[subnets.T-iAulsf.subnets.B_C.balances]
ELJZq4 = "5329060183113942323"
XQnNCy0Z = "8335468711507992019"
_L0_-p = "1"

[subnets.T-iAulsf.subnets.B_C.nodes.JP_K]
ethapi = true
seed_nodes = []
parent_node = "9d6"

[subnets.T-iAulsf.subnets.B_C.nodes.JP_K.mode]
Validator = "ELJZq4"

[subnets.T-iAulsf.subnets.B_C.nodes.Kl1]
ethapi = true
seed_nodes = ["JP_K"]
parent_node = "g72w"

[subnets.T-iAulsf.subnets.B_C.nodes.Kl1.mode]
Validator = "TD-cbBcg"

[subnets.T-iAulsf.subnets.B_C.nodes.SlZ]
ethapi = true
seed_nodes = ["JP_K"]
parent_node = "jxMoQdMT"

[subnets.T-iAulsf.subnets.B_C.nodes.SlZ.mode]
Validator = "_9B"

[subnets.T-iAulsf.subnets.B_C.relayers.6zITyKv]
submitter = "_9B"
follow_node = "JP_K"
submit_node = "R6Q"

[subnets.T-iAulsf.subnets.B_C.relayers.VPr]
submitter = "XQnNCy0Z"
follow_node = "Kl1"
submit_node = "R6Q"

[subnets.T-iAulsf.subnets.B_C.subnets]
