[accounts.H_8]

[accounts.PiA9UjDX]

[accounts.QBuAltVa]

[rootnet]
type = "New"

[rootnet.validators]
H_8 = "7446791919045725731"

[rootnet.balances]
H_8 = "100000000000000000000"
PiA9UjDX = "100000000000000000000"
QBuAltVa = "100000000000000000000"

[rootnet.nodes.y3s_Rg]
ethapi = true

[rootnet.nodes.y3s_Rg.mode]
type = "Validator"
validator = "H_8"

[rootnet.env]
CMT__ELJkq1 = "/⁑퀿􏿿>"
CMT__T7X1q = "^鼋¨𧫴㡁"
CMT__ZHjWCT = "|琞u⁎p!/؜"
CMT__vjwWQus = "-[>￵0>/"

[subnets.U2exi_7]
creator = "H_8"

[subnets.U2exi_7.validators]
QBuAltVa = "1"

[subnets.U2exi_7.balances]
H_8 = "5484685668981792050"

[subnets.U2exi_7.nodes.NeSYWY_z]
ethapi = true
parent_node = "y3s_Rg"

[subnets.U2exi_7.nodes.NeSYWY_z.mode]
type = "Validator"
validator = "QBuAltVa"

[subnets.U2exi_7.relayers.7LwijvRU]
submitter = "H_8"
follow_node = "NeSYWY_z"
submit_node = "y3s_Rg"

[subnets.U2exi_7.relayers.7Z1W6_]
submitter = "H_8"
follow_node = "NeSYWY_z"
submit_node = "y3s_Rg"

[subnets.U2exi_7.bottom_up_checkpoint]
period = 70244

[subnets.U2exi_7.env]
CMT__U5AkvAyG = "8~"
FM__uSmNR = "!"

[subnets.qzGfE]
creator = "PiA9UjDX"

[subnets.qzGfE.validators]
H_8 = "2092174042536407337"
PiA9UjDX = "1104764474287520028"

[subnets.qzGfE.balances]
QBuAltVa = "6572006061783134332"

[subnets.qzGfE.nodes.BUBbm-HQ]
ethapi = false
parent_node = "y3s_Rg"

[subnets.qzGfE.nodes.BUBbm-HQ.mode]
type = "Validator"
validator = "H_8"

[subnets.qzGfE.nodes.Kl6QJ]
ethapi = false
seed_nodes = ["BUBbm-HQ"]
parent_node = "y3s_Rg"

[subnets.qzGfE.nodes.Kl6QJ.mode]
type = "Validator"
validator = "PiA9UjDX"

[subnets.qzGfE.relayers.0kz]
submitter = "H_8"
follow_node = "Kl6QJ"
submit_node = "y3s_Rg"

[subnets.qzGfE.relayers.k2zN3_]
submitter = "PiA9UjDX"
follow_node = "Kl6QJ"
submit_node = "y3s_Rg"

[subnets.qzGfE.relayers.n42Xt]
submitter = "H_8"
follow_node = "Kl6QJ"
submit_node = "y3s_Rg"

[subnets.qzGfE.bottom_up_checkpoint]
period = 60172

[subnets.qzGfE.env]
CMT__6Ty3 = "9 |Q#|‚%"
CMT__ehU9e7jj = "⁯i쨖qt"
FM__qOpLv1LA = "!⁤/\u001EN虥"
FM__tMxZi6g = ""
