[accounts.YamwZAKu]

[accounts.mnrAR]

[accounts.q_g]

[rootnet]
type = "New"

[rootnet.validators]
mnrAR = "9744082597575754275"
q_g = "271564365291395932"

[rootnet.balances]
YamwZAKu = "100000000000000000000"
mnrAR = "100000000000000000000"
q_g = "100000000000000000000"

[rootnet.nodes.0l4]
ethapi = true
seed_nodes = ["A5U6o"]

[rootnet.nodes.0l4.mode]
type = "Validator"
validator = "q_g"

[rootnet.nodes.A5U6o]
ethapi = true

[rootnet.nodes.A5U6o.mode]
type = "Validator"
validator = "mnrAR"

[subnets.AfqSoZ]
creator = "YamwZAKu"

[subnets.AfqSoZ.validators]
YamwZAKu = "5024549145878342784"
q_g = "1"

[subnets.AfqSoZ.balances]
YamwZAKu = "7736736546968286438"
mnrAR = "896771437412042153"

[subnets.AfqSoZ.nodes.42V2dlA2]
ethapi = true
seed_nodes = ["X5HAAp"]
parent_node = "0l4"

[subnets.AfqSoZ.nodes.42V2dlA2.mode]
type = "Full"

[subnets.AfqSoZ.nodes.X5HAAp]
ethapi = false
parent_node = "0l4"

[subnets.AfqSoZ.nodes.X5HAAp.mode]
type = "Validator"
validator = "YamwZAKu"

[subnets.AfqSoZ.relayers.6gB]
submitter = "mnrAR"
follow_node = "X5HAAp"
submit_node = "A5U6o"

[subnets.AfqSoZ.relayers._3u71]
submitter = "q_g"
follow_node = "X5HAAp"
submit_node = "A5U6o"

[subnets.AfqSoZ.subnets.QB8]
creator = "YamwZAKu"

[subnets.AfqSoZ.subnets.QB8.validators]
mnrAR = "445325375349600925"

[subnets.AfqSoZ.subnets.QB8.balances]
YamwZAKu = "7424706495210709581"
mnrAR = "6004979205443301323"

[subnets.AfqSoZ.subnets.QB8.nodes.kk4_G-]
ethapi = false
parent_node = "X5HAAp"

[subnets.AfqSoZ.subnets.QB8.nodes.kk4_G-.mode]
type = "Validator"
validator = "mnrAR"

[subnets.AfqSoZ.subnets.QB8.relayers.jKKMMJA]
submitter = "mnrAR"
follow_node = "kk4_G-"
submit_node = "42V2dlA2"
