[accounts.47B3BbT]

[accounts.iJ32]

[accounts.jnqduIaQ]

[rootnet]
type = "New"

[rootnet.validators]
iJ32 = "2482914694179010604"

[rootnet.balances]
47B3BbT = "100000000000000000000"
iJ32 = "100000000000000000000"
jnqduIaQ = "100000000000000000000"

[rootnet.nodes.23W]
ethapi = false
seed_nodes = []

[rootnet.nodes.23W.mode]
type = "Validator"
validator = "iJ32"

[subnets.g8zHwBN]
creator = "iJ32"

[subnets.g8zHwBN.validators]
jnqduIaQ = "5189884830813007041"

[subnets.g8zHwBN.balances]
47B3BbT = "9999999999999999999"

[subnets.g8zHwBN.nodes.7eDxRM8E]
ethapi = false
seed_nodes = []
parent_node = "23W"

[subnets.g8zHwBN.nodes.7eDxRM8E.mode]
type = "Validator"
validator = "jnqduIaQ"

[subnets.g8zHwBN.relayers.BonKZBB7]
submitter = "jnqduIaQ"
follow_node = "7eDxRM8E"
submit_node = "23W"

[subnets.g8zHwBN.relayers.tp_Y]
submitter = "jnqduIaQ"
follow_node = "7eDxRM8E"
submit_node = "23W"

[subnets.g8zHwBN.subnets.Zp-5etX]
creator = "jnqduIaQ"

[subnets.g8zHwBN.subnets.Zp-5etX.validators]
47B3BbT = "3261699815520283256"

[subnets.g8zHwBN.subnets.Zp-5etX.balances]

[subnets.g8zHwBN.subnets.Zp-5etX.nodes.00IEmgAA]
ethapi = true
seed_nodes = []
parent_node = "7eDxRM8E"

[subnets.g8zHwBN.subnets.Zp-5etX.nodes.00IEmgAA.mode]
type = "Validator"
validator = "47B3BbT"

[subnets.g8zHwBN.subnets.Zp-5etX.relayers.AsNlcZya]
submitter = "jnqduIaQ"
follow_node = "00IEmgAA"
submit_node = "7eDxRM8E"

[subnets.g8zHwBN.subnets.Zp-5etX.subnets]
