[accounts.ID72]

[accounts.oyn]

[accounts.x_52Lm]

[rootnet]
type = "External"

[rootnet.deployment]
type = "New"
deployer = "ID72"

[subnets.EQxjKGFA]
creator = "ID72"

[subnets.EQxjKGFA.validators]
x_52Lm = "8209706277064916472"

[subnets.EQxjKGFA.balances]
oyn = "2305445625663596816"

[subnets.EQxjKGFA.nodes.HLT_z0G]
ethapi = true
seed_nodes = []

[subnets.EQxjKGFA.nodes.HLT_z0G.mode]
type = "Validator"
validator = "x_52Lm"

[subnets.EQxjKGFA.relayers.E7xcJm]
submitter = "oyn"
follow_node = "HLT_z0G"

[subnets.EQxjKGFA.relayers.x7_jB6]
submitter = "x_52Lm"
follow_node = "HLT_z0G"

[subnets.EQxjKGFA.subnets.aWn]
creator = "oyn"

[subnets.EQxjKGFA.subnets.aWn.validators]
ID72 = "3259809290142443537"
oyn = "6012373228910588906"

[subnets.EQxjKGFA.subnets.aWn.balances]
oyn = "5080983028490214972"
x_52Lm = "7333971111540430540"

[subnets.EQxjKGFA.subnets.aWn.nodes._rtaW_H]
ethapi = false
seed_nodes = []
parent_node = "HLT_z0G"

[subnets.EQxjKGFA.subnets.aWn.nodes._rtaW_H.mode]
type = "Validator"
validator = "ID72"

[subnets.EQxjKGFA.subnets.aWn.nodes.iHgPl_F]
ethapi = false
seed_nodes = ["_rtaW_H"]
parent_node = "HLT_z0G"

[subnets.EQxjKGFA.subnets.aWn.nodes.iHgPl_F.mode]
type = "Validator"
validator = "oyn"

[subnets.EQxjKGFA.subnets.aWn.relayers.OF2iQ_]
submitter = "ID72"
follow_node = "_rtaW_H"
submit_node = "HLT_z0G"

[subnets.EQxjKGFA.subnets.aWn.relayers.hMUxqmPQ]
submitter = "oyn"
follow_node = "_rtaW_H"
submit_node = "HLT_z0G"

[subnets.EQxjKGFA.subnets.aWn.relayers.vR_1]
submitter = "ID72"
follow_node = "_rtaW_H"
submit_node = "HLT_z0G"

[subnets.EQxjKGFA.subnets.aWn.subnets]
