[package]
name = "fendermint_actor_machine"
description = "Shared types for ADM machine actors"
license.workspace = true
edition.workspace = true
authors.workspace = true
version = "0.1.0"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
fil_actors_runtime = { workspace = true }
fil_actor_adm = { workspace = true }
fil_actors_evm_shared = { workspace = true }
frc42_dispatch = { workspace = true }
fvm_ipld_blockstore = { workspace = true }
fvm_ipld_encoding = { workspace = true }
fvm_shared = { workspace = true }
multihash = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
fil_actors_evm_shared = { workspace = true }
fil_actors_runtime = { workspace = true, features = ["test_utils"] }
hex = { workspace = true }

[features]
fil-actor = ["fil_actors_runtime/fil-actor"]
