[package]
name = "fendermint_actor_machine"
description = "Shared types for ADM machine actors"
license.workspace = true
edition.workspace = true
authors.workspace = true
version = "0.1.0"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anyhow = { workspace = true }
fil_actors_runtime = { workspace = true }
fil_actor_adm = { workspace = true }
frc42_dispatch = { workspace = true }
fvm_ipld_blockstore = { workspace = true }
fvm_ipld_encoding = { workspace = true }
fvm_shared = { workspace = true }
recall_sol_facade = { workspace = true, features = ["machine"] }
serde = { workspace = true, features = ["derive"] }
recall_actor_sdk = { path = "../../../recall/actor_sdk" }

[dev-dependencies]
fil_actors_runtime = { workspace = true, features = ["test_utils"] }

[features]
fil-actor = ["fil_actors_runtime/fil-actor"]
