[package]
name = "fendermint_vm_encoding"
description = "Utilities for encoding some of the primitive FVM types with serde"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true


[dependencies]
serde = { workspace = true }
serde_with = { workspace = true }
num-traits = { workspace = true }

cid = { workspace = true }
fvm_shared = { workspace = true }
ipc-api = { workspace = true }
