// Create index.ts file to export all tasks
import './deploy-libraries'
import './deploy-gateway'
import './deploy-registry'
import './deploy'
import './upgrade'
import './validator-gater'
import './validator-rewarder'
import './gen-selector-library'
import './cross-network-messenger'
