[package]
name = "fendermint_eth_hardhat_builtin"
description = "Utilities to deal with Hardhat build artifacts"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
ethers-core = { workspace = true }
hex = { workspace = true }
fs-err = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
color-eyre = { workspace = true }
fs-err = { workspace = true }
num-traits = { workspace = true }
toml = "0.8.19"
cargo_metadata = "0.19"
ignore = "0.4"
tracing = "0.1"
build-rs-utils = { path = "../../../build-rs-utils" }
which = "7"
fendermint_eth_hardhat = { path = "../hardhat" }
