[package]
name = "fendermint_vm_iroh_resolver"
description = "Resolve iroh content in messages"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-stm = { workspace = true }
im = { workspace = true }
iroh = { workspace = true }
libp2p = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }

ipc-api = { workspace = true }
ipc_ipld_resolver = { workspace = true }

fendermint_vm_topdown = { path = "../topdown" }

[dev-dependencies]
rand = { workspace = true }
tokio = { workspace = true }
