# About promtail: https://grafana.com/docs/loki/latest/send-data/promtail/
# Configuring promtail: https://grafana.com/docs/loki/latest/send-data/promtail/configuration/
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
      - url: http://host.docker.internal:3100/loki/api/v1/push

scrape_configs:
  - job_name: flog_scrape

    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["logging=promtail"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_logging_jobname']
        target_label: 'job'

    # docker_sd_configs:
    #   - host: unix:///var/run/docker.sock
    # relabel_configs:
    #   - action: replace
    #     source_labels:
    #       - __meta_docker_container_name
    #     target_label: docker_container_stdout

  - job_name: fendermint
    static_configs:
      - targets:
        - localhost
      - labels:
          job: fendermint_log
          __path__: /var/log/fendermint/*.log
  - job_name: system
    static_configs:
    - targets:
        - localhost
    - labels:
        job: varlogs
        __path__: /var/log/*log
