# About promtail: https://grafana.com/docs/loki/latest/send-data/promtail/
# Configuring promtail: https://grafana.com/docs/loki/latest/send-data/promtail/configuration/
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

scrape_configs:
  - job_name: flog_scrape
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - action: replace
        source_labels:
          - __meta_docker_container_name
        target_label: docker_container_stdout
  - job_name: fendermint
    static_configs:
      - targets:
        - localhost
      - labels:
          job: fendermint_log
          __path__: /var/log/fendermint/*.log
