// DO NOT EDIT! This file was generated by build.rs
#[macro_use]
mod convert;
#[allow(clippy::all)]
pub mod i_diamond;
#[allow(clippy::all)]
pub mod diamond_loupe_facet;
#[allow(clippy::all)]
pub mod diamond_cut_facet;
#[allow(clippy::all)]
pub mod ownership_facet;
#[allow(clippy::all)]
pub mod gateway_diamond;
#[allow(clippy::all)]
pub mod gateway_manager_facet;
#[allow(clippy::all)]
pub mod gateway_getter_facet;
#[allow(clippy::all)]
pub mod checkpointing_facet;
#[allow(clippy::all)]
pub mod top_down_finality_facet;
#[allow(clippy::all)]
pub mod xnet_messaging_facet;
#[allow(clippy::all)]
pub mod gateway_messenger_facet;
