[tasks.docker-network-create]
command = "docker"
args = ["network", "create", "${NETWORK_NAME}"]
ignore_errors = true

[tasks.docker-network-rm]
command = "docker"
args = ["network", "rm", "${NETWORK_NAME}"]
ignore_errors = true

[tasks.docker-stop]
command = "docker"
args = ["stop", "${CONTAINER_NAME}"]
ignore_errors = true

[tasks.docker-rm]
command = "docker"
args = ["rm", "--force", "${CONTAINER_NAME}"]
ignore_errors = true

[tasks.docker-destroy]
run_task = { name = [
  "docker-stop",
  "docker-rm",
] }

[tasks.docker-logs]
command = "docker"
args = ["logs", "${CONTAINER_NAME}"]
ignore_errors = true
