[package]
name = "recall_kernel"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
ambassador = { workspace = true }
anyhow = { workspace = true }
fvm = { workspace = true }
fvm_ipld_blockstore = { workspace = true }
fvm_shared = { workspace = true }

recall_kernel_ops = { path = "./ops" }
recall_syscalls = { path = "../syscalls" }
