[package]
name = "iroh_manager"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
num-traits = { workspace = true }
iroh = { workspace = true }
iroh-blobs = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
n0-future = { workspace = true}
quic-rpc= { workspace = true, features = ["quinn-transport", "test-utils"] }
iroh-quinn = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tracing-subscriber = { workspace = true }
