[package]
name = "iroh_manager"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
iroh = { workspace = true }
iroh-blobs = { workspace = true }
iroh-quinn = { workspace = true }
iroh-relay = { workspace = true }
n0-future = { workspace = true }
num-traits = { workspace = true }
quic-rpc = { workspace = true, features = ["quinn-transport", "test-utils"] }
tokio = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tracing-subscriber = { workspace = true }
