[package]
name = "ipc-provider"
description = "The provider to interact with IPC"
version = "0.1.0"
edition.workspace = true
license-file.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
async-channel = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
cid = { workspace = true }
dirs = { workspace = true }
ethers = { workspace = true }
ethers-contract = { workspace = true }
futures-util = { workspace = true }
hex = { workspace = true }
http = { workspace = true }
libsecp256k1 = { workspace = true }
log = { workspace = true }
num-traits = { workspace = true }
num-derive = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
serde_tuple = { workspace = true }
serde_with = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
toml = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
zeroize = { workspace = true }

fil_actors_runtime = { workspace = true }
fvm_ipld_encoding = { workspace = true }
fvm_shared = { workspace = true }

ipc-types = { workspace = true }
ipc-wallet = { workspace = true, features = ["with-ethers"] }
ipc-api = { workspace = true }
ipc_actors_abis = { workspace = true }
ipc-observability = { workspace = true }
prometheus = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
hex = { workspace = true }
indoc = "2.0.0"
