[package]
name = "fendermint_vm_event"
description = "Defines the event type emitted in fendermint"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = { workspace = true }
