[package]
name = "recall_actor_sdk"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
fvm_shared = { workspace = true }
fvm_sdk = { workspace = true }
num-traits = { workspace = true }
