[package]
name = "recall_actor_sdk"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
fvm_shared = { workspace = true }
fvm_sdk = { workspace = true }
num-traits = { workspace = true }
fil_actors_runtime = { workspace = true }
recall_sol_facade = { workspace = true, features = [] }
anyhow = { workspace = true }
fvm_ipld_encoding = { workspace = true }
serde = { workspace = true }
cid = { workspace = true }
