const test = require("node:test");
const assert = require("node:assert/strict");
const { applyAntiCheat } = require("../src/anticheat");

function basePR() {
  return {
    number: 1,
    additions: 100,
    deletions: 50,
    comments: [],
    files: [],
    analysis: { weight_multiplier: 1.0 },
  };
}

test("pattern 1 triggers relocation downweight", () => {
  const pr = basePR();
  pr.files = [
    {
      filename: "foo.ts",
      status: "renamed",
      additions: 80,
      deletions: 70,
      patch: "-const a = 1;\n+const a = 1;",
    },
  ];
  const result = applyAntiCheat({ prs: [pr], commits: [], commitDetailsBySha: {} });
  assert.equal(result.gaming_flags.length > 0, true);
  assert.equal(pr.analysis.weight_multiplier <= 0.1, true);
});

test("pattern 1 does not trigger for dissimilar patches", () => {
  const pr = basePR();
  pr.files = [{ filename: "bar.ts", status: "modified", additions: 10, deletions: 5, patch: "-a\n+b\n+c" }];
  const result = applyAntiCheat({ prs: [pr], commits: [], commitDetailsBySha: {} });
  assert.equal(result.gaming_flags.length, 0);
  assert.equal(pr.analysis.weight_multiplier, 1);
});

test("pattern 2 formatter commit excluded", () => {
  const commits = [{ sha: "abc", commit: { message: "refactor style" } }];
  const details = { abc: { files: [{ patch: "+  \n-  " }, { patch: "+;\n-;" }] } };
  const result = applyAntiCheat({ prs: [], commits, commitDetailsBySha: details });
  assert.equal(result.adjusted.weighted_commits, 0);
  assert.equal(result.adjusted.excluded_commits, 1);
});

test("pattern 2 non-formatter commit included", () => {
  const commits = [{ sha: "def", commit: { message: "real fix for bug" } }];
  const details = { def: { files: [{ patch: "-x=1\n+x=2" }] } };
  const result = applyAntiCheat({ prs: [], commits, commitDetailsBySha: details });
  assert.equal(result.adjusted.weighted_commits, 1);
});

test("pattern 3 generated file gets heavy discount", () => {
  const pr = basePR();
  pr.additions = 300;
  pr.files = [{ filename: "api.generated.ts", status: "added", additions: 300, deletions: 0, patch: "+Code generated by tool" }];
  const result = applyAntiCheat({ prs: [pr], commits: [], commitDetailsBySha: {} });
  assert.equal(result.adjusted.effective_lines_added < 100, true);
});

test("pattern 3 normal file stays near full weight", () => {
  const pr = basePR();
  pr.additions = 80;
  pr.files = [{ filename: "service.ts", status: "modified", additions: 80, deletions: 0, patch: "+function run() {}" }];
  const result = applyAntiCheat({ prs: [pr], commits: [], commitDetailsBySha: {} });
  assert.equal(result.adjusted.effective_lines_added, 80);
});

test("pattern 4 commit message inflation excludes known noise terms", () => {
  const commits = [{ sha: "ghi", commit: { message: "whitespace cleanup" } }];
  const result = applyAntiCheat({ prs: [], commits, commitDetailsBySha: { ghi: { files: [{ patch: "-a\n+b" }] } } });
  assert.equal(result.adjusted.weighted_commits, 0);
});

test("pattern 4 short commit messages are downweighted to 0.3", () => {
  const commits = [{ sha: "jkl", commit: { message: "tiny fix" } }];
  const result = applyAntiCheat({ prs: [], commits, commitDetailsBySha: { jkl: { files: [{ patch: "-a\n+b" }] } } });
  assert.equal(result.adjusted.weighted_commits, 0.3);
});
