
keystore_path = "~/.ipc"

# Filecoin Calibration
[[subnets]]
id = "/r314159"

[subnets.config]
network_type = "fevm"
provider_http = "https://calibration.filfox.info/rpc/v1"
gateway_addr = "<< to be replaced by script >>"
registry_addr = "<< to be replaced by script >>"

# Subnet template - uncomment and adjust before using
[[subnets]]
id = "<< to be replaced by script >>"

[subnets.config]
network_type = "fevm"
provider_http = "http://127.0.0.1:8745"
# from genesis
gateway_addr = "0x77aa40b105843728088c0132e43fc44348881da8"
# from genesis
registry_addr = "0x74539671a1d2f1c8f200826baba665179f53a1b7"
