
keystore_path = "~/.ipc"

# Filecoin Calibration
[[subnets]]
id = "/r314159"

[subnets.config]
network_type = "fevm"
provider_http = "https://calibration.filfox.info/rpc/v1"
# To be replaced by deploy.sh
gateway_addr = "0xBF7a836AF7F1A1EdB939Ff2230Cd41a5e8e5C387"
# To be replaced by deploy.sh
registry_addr = "0xb1110ba6507fb5f89E12Aff23C658449D11d8708"

# Subnet template - uncomment and adjust before using
[[subnets]]
# To be replaced by deploy.sh
id = "/r314159/t410flp4jf7keqcf5bqogrkx4wpkygiskykcvpaigicq"

[subnets.config]
network_type = "fevm"
provider_http = "http://127.0.0.1:8745"
# from genesis
gateway_addr = "0x77aa40b105843728088c0132e43fc44348881da8"
# from genesis
registry_addr = "0x74539671a1d2f1c8f200826baba665179f53a1b7"
