// Copyright 2022-2024 Protocol Labs
// SPDX-License-Identifier: Apache-2.0, MIT

//! Build script for auto-discovering plugins.
//!
//! This script scans the plugins/ directory and generates code to load
//! plugins based on enabled feature flags. No plugin names are hardcoded!

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=../../plugins");

    let plugins_dir = Path::new("../../plugins");
    if !plugins_dir.exists() {
        // No plugins directory - generate empty selector
        generate_empty_selector();
        return;
    }

    let mut plugin_code = String::new();
    plugin_code.push_str("// Auto-generated by build.rs - DO NOT EDIT\n");
    plugin_code.push_str("// This file is regenerated on each build\n\n");
    plugin_code.push_str("use std::sync::Arc;\n\n");

    // Collect enabled plugins
    let mut enabled_plugins = Vec::new();

    // Scan plugins directory
    if let Ok(entries) = fs::read_dir(plugins_dir) {
        for entry in entries.flatten() {
            if !entry.path().is_dir() {
                continue;
            }

            let plugin_name = entry.file_name().to_string_lossy().to_string();
            let feature_name = format!("plugin-{}", plugin_name);
            let feature_var = format!(
                "CARGO_FEATURE_PLUGIN_{}",
                plugin_name.to_uppercase().replace("-", "_").replace(" ", "_")
            );

            // Check if this plugin's feature is enabled
            if env::var(&feature_var).is_ok() {
                let crate_name = format!("ipc_plugin_{}", plugin_name.replace("-", "_"));

                println!("cargo:info=Discovered plugin: {} (feature: {})", plugin_name, feature_name);

                plugin_code.push_str(&format!(
                    "#[cfg(feature = \"{}\")]\n",
                    feature_name
                ));
                plugin_code.push_str(&format!(
                    "extern crate {} as plugin_{};\n\n",
                    crate_name,
                    plugin_name.replace("-", "_")
                ));

                enabled_plugins.push((feature_name, plugin_name));
            }
        }
    }

    // Generate type alias for the active module
    plugin_code.push_str("/// The active module type - changes based on enabled features.\n");
    plugin_code.push_str("///\n");
    plugin_code.push_str("/// This is auto-generated by the build script based on enabled feature flags.\n");

    if enabled_plugins.is_empty() {
        plugin_code.push_str("pub type DiscoveredModule = fendermint_module::NoOpModuleBundle;\n\n");
    } else {
        // Use the first enabled plugin as the module type
        let (feature, plugin_name) = &enabled_plugins[0];
        let plugin_var = plugin_name.replace("-", "_");

        plugin_code.push_str(&format!(
            "#[cfg(feature = \"{}\")]\n",
            feature
        ));
        plugin_code.push_str(&format!(
            "pub type DiscoveredModule = plugin_{}::StorageNodeModule;\n\n",
            plugin_var
        ));
        plugin_code.push_str(&format!("#[cfg(not(feature = \"{}\"))]\n", feature));
        plugin_code.push_str("pub type DiscoveredModule = fendermint_module::NoOpModuleBundle;\n\n");
    }

    // Generate loading function
    plugin_code.push_str("/// Load the active plugin instance.\n");
    plugin_code.push_str("pub fn load_discovered_plugin() -> Arc<DiscoveredModule> {\n");

    for (feature, plugin_name) in &enabled_plugins {
        let plugin_var = plugin_name.replace("-", "_");
        plugin_code.push_str(&format!(
            "    #[cfg(feature = \"{}\")]\n",
            feature
        ));
        plugin_code.push_str("    {\n");
        plugin_code.push_str(&format!(
            "        tracing::info!(\"Auto-discovered plugin: {}\");\n",
            plugin_name
        ));
        plugin_code.push_str(&format!(
            "        return Arc::new(plugin_{}::create_plugin());\n",
            plugin_var
        ));
        plugin_code.push_str("    }\n\n");
    }

    plugin_code.push_str("    // No plugin enabled\n");
    plugin_code.push_str("    tracing::info!(\"No plugin enabled, using NoOpModuleBundle\");\n");
    plugin_code.push_str("    Arc::new(fendermint_module::NoOpModuleBundle::default())\n");
    plugin_code.push_str("}\n");

    // Write generated code
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("discovered_plugins.rs");
    fs::write(&dest_path, plugin_code).expect("Failed to write discovered_plugins.rs");

    println!("cargo:info=Generated plugin discovery code at {:?}", dest_path);
}

fn generate_empty_selector() {
    let plugin_code = "// No plugins directory found\n\
        use fendermint_module::NoOpModuleBundle;\n\
        use std::sync::Arc;\n\n\
        pub type DiscoveredModule = NoOpModuleBundle;\n\n\
        pub fn load_discovered_plugin() -> Arc<DiscoveredModule> {\n\
            Arc::new(NoOpModuleBundle::default())\n\
        }\n";

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("discovered_plugins.rs");
    fs::write(&dest_path, plugin_code).expect("Failed to write discovered_plugins.rs");
}
