[package]
name = "contracts-artifacts"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
license-file.workspace = true

[dependencies]
anyhow = { workspace = true }
tempfile = { workspace = true }
rust-embed = "6.4.0"
