version: '3.8'

services:
  faucet:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ipc-faucet
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - RPC_URL=${RPC_URL:-http://node-1.test.ipc.space:8545}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - FAUCET_AMOUNT=${FAUCET_AMOUNT:-1}
      - RATE_LIMIT_WINDOW=${RATE_LIMIT_WINDOW:-86400000}
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX:-1}
      - SERVE_STATIC=true
      - ENABLE_CORS=false
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

