const GENERATED_FILE_PATTERNS = [
  /\.pb\.go$/i,
  /\.generated\.ts$/i,
  /_gen\./i,
  /^\d{14}_.*\.sql$/i,
];

const MESSAGE_EXCLUDE_RE = /\b(fix typo|formatting|whitespace|prettier|lint|nit)\b/i;
const WHITESPACE_DIFF_RE = /^[+-]\s*[;,{}()[\]]*\s*$/;

function normaliseLine(line) {
  return line.replace(/\s+/g, "");
}

function extractDiffLines(patch = "") {
  const lines = patch.split("\n");
  const added = [];
  const removed = [];
  for (const line of lines) {
    if (line.startsWith("+++ ") || line.startsWith("--- ")) {
      continue;
    }
    if (line.startsWith("+")) {
      added.push(normaliseLine(line.slice(1)));
    } else if (line.startsWith("-")) {
      removed.push(normaliseLine(line.slice(1)));
    }
  }
  return { added, removed };
}

function jaccardSimilarity(a, b) {
  const setA = new Set(a.filter(Boolean));
  const setB = new Set(b.filter(Boolean));
  if (!setA.size && !setB.size) {
    return 1;
  }
  const intersection = new Set([...setA].filter((x) => setB.has(x))).size;
  const union = new Set([...setA, ...setB]).size || 1;
  return intersection / union;
}

function isGeneratedFile(file) {
  if (GENERATED_FILE_PATTERNS.some((re) => re.test(file.filename || ""))) {
    return true;
  }
  const patch = file.patch || "";
  const fingerprints = ["DO NOT EDIT", "Code generated by", "This file was generated"];
  return fingerprints.some((s) => patch.includes(s));
}

function isFormatterCommit(commitDetail) {
  const files = commitDetail.files || [];
  if (!files.length) {
    return false;
  }
  return files.every((file) => {
    const patch = file.patch || "";
    if (!patch) {
      return false;
    }
    const changed = patch
      .split("\n")
      .filter((line) => line.startsWith("+") || line.startsWith("-"))
      .filter((line) => !line.startsWith("+++ ") && !line.startsWith("--- "));
    return changed.length > 0 && changed.every((line) => WHITESPACE_DIFF_RE.test(line));
  });
}

function applyAntiCheat({ prs, commits, commitDetailsBySha }) {
  const flags = [];
  let rawLinesAdded = 0;
  let effectiveLinesAdded = 0;
  let weightedCommits = 0;
  let excludedCommits = 0;

  for (const pr of prs) {
    rawLinesAdded += Number(pr.additions || 0);
    let relocatedLines = 0;
    let changedLines = 0;
    const flaggedFiles = [];

    for (const file of pr.files || []) {
      const additions = Number(file.additions || 0);
      const deletions = Number(file.deletions || 0);
      const localChanged = additions + deletions;
      changedLines += localChanged;

      const { added, removed } = extractDiffLines(file.patch || "");
      const similarity = jaccardSimilarity(added, removed);
      if ((file.status === "added" || file.status === "renamed") && similarity > 0.85) {
        relocatedLines += localChanged;
        flaggedFiles.push({ file: file.filename, similarity });
      }

      let fileWeight = 1.0;
      const generated = isGeneratedFile(file);
      const likelyGeneratedLargeAdd = additions > 200 && (!pr.comments || pr.comments.length === 0);
      if (generated || likelyGeneratedLargeAdd) {
        fileWeight = 0.1;
      }
      effectiveLinesAdded += additions * fileWeight;
    }

    const relocatedRatio = changedLines > 0 ? relocatedLines / changedLines : 0;
    if (relocatedRatio > 0.6) {
      const original = Number(pr.analysis?.weight_multiplier ?? 1.0);
      const overridden = Math.max(0.05, original * 0.1);
      if (pr.analysis) {
        pr.analysis.weight_multiplier = overridden;
      }
      flags.push({
        pattern: "code_relocation_without_modification",
        affected_prs: [pr.number],
        description: `Relocation ratio ${(relocatedRatio * 100).toFixed(1)}% across ${flaggedFiles.length} file(s).`,
        weight_applied: overridden,
      });
    }
  }

  for (const commit of commits) {
    const sha = commit.sha;
    const message = commit.commit?.message || "";
    const detail = commitDetailsBySha[sha] || {};
    const lower = message.toLowerCase();

    if (lower.startsWith("merge ") || lower.startsWith("revert ")) {
      excludedCommits += 1;
      continue;
    }

    if (MESSAGE_EXCLUDE_RE.test(message)) {
      excludedCommits += 1;
      continue;
    }

    if (isFormatterCommit(detail)) {
      excludedCommits += 1;
      continue;
    }

    if (message.trim().length < 10) {
      weightedCommits += 0.3;
      flags.push({
        pattern: "commit_message_inflation",
        affected_prs: [],
        description: `Low-quality short commit message on ${sha.slice(0, 8)}`,
        weight_applied: 0.3,
      });
      continue;
    }

    weightedCommits += 1;
  }

  const rawInflationPct = rawLinesAdded > 0 ? Math.round((1 - effectiveLinesAdded / rawLinesAdded) * 100) : 0;

  return {
    adjusted: {
      weighted_commits: Number(weightedCommits.toFixed(2)),
      effective_lines_added: Math.round(effectiveLinesAdded),
      inflation_removed_pct: rawInflationPct,
      excluded_commits: excludedCommits,
    },
    gaming_flags: flags,
  };
}

module.exports = {
  applyAntiCheat,
  extractDiffLines,
  isFormatterCommit,
  jaccardSimilarity,
};
