[profile.default]
# contracts are stored under the conventional directory instead of Foundry's src/ default.
src = "contracts"
# no_storage_caching = true
block_gas_limit = 10000000000
optimizer_runs=200
# via_ir = true
# eth_rpc_url = "https://api.hyperspace.node.glif.io/rpc/v1"
memory_limit =  2147483648 # 2GB
# [profile.default.optimizer_details]
# constantOptimizer = true
# yul = false
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "fevmate/=node_modules/fevmate/",
    "forge-std/=lib/forge-std/src/",
    "murky/=lib/murky/src/",
    "elliptic-curve-solidity/=node_modules/elliptic-curve-solidity/"
]

[fuzz]
runs = 512

[invariant]
call_override = false  # Override calls
runs          = 50     # The number of times to run the invariant tests
depth         = 200    # The number of calls to make in the invariant tests

[profile.no_revert.invariant]
fail_on_revert = true   # Fail the test if the contract reverts

[profile.allow_revert.invariant]
fail_on_revert = false   # Fail the test if the contract reverts

## dummy trigger ci