[package]
name = "fendermint_actor_blob_reader"
description = "Singleton actor for reading blob bytes"
license.workspace = true
edition.workspace = true
authors.workspace = true
version = "0.1.0"

[lib]
## lib is necessary for integration tests
## cdylib is necessary for Wasm build
crate-type = ["cdylib", "lib"]

[dependencies]
anyhow = { workspace = true }
data-encoding = { workspace = true }
log = { workspace = true, features = ["std"] }
num-traits = { workspace = true }
fil_actors_runtime = { workspace = true }
fvm_ipld_encoding = { workspace = true }
fvm_ipld_blockstore = { workspace = true }
fvm_shared = { workspace = true }
frc42_dispatch = { workspace = true }
num-derive = { workspace = true }
sha2 = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_tuple = { workspace = true }

fendermint_actor_blobs_shared = { path = "../blobs/shared" }


[dev-dependencies]
fil_actors_evm_shared = { workspace = true }
fil_actors_runtime = { workspace = true, features = ["test_utils"] }
hex-literal = { workspace = true }
iroh-base = { workspace = true, features = ["key"] }
rand = { workspace = true }

[features]
fil-actor = ["fil_actors_runtime/fil-actor"]
