extend = [
  { path = "../fendermint/scripts/docker.toml" },
]

[tasks.prometheus-start]
env = { "CONTAINER_NAME" = "ipc-prometheus" }
script = "docker run --name ${CONTAINER_NAME} -d -p 9090:9090 -v ./prometheus.yml:/etc/prometheus/prometheus.yml prom/prometheus"

[tasks.prometheus-destroy]
env = { "CONTAINER_NAME" = "Prometheus" }
run_task = "docker-destroy"

[tasks.default]
clear = true
script_runner = "@duckscript"
script = [
  '''
    echo
    echo How to use:
    echo
    echo Run 'cargo make prometheus-pull' to pull the latest Prometheus docker image.
    echo Run 'cargo make prometheus-start' to start Prometheus. You can then visit http://localhost:9090 for Prometheus web UI.
    echo Run 'cargo make prometheus-destroy' to stop Prometheus.
    echo
''',
]
