[package]
name = "fendermint_actor_fluence"
description = "Fluence actor to call the RandomX syscall"
version = "12.0.0"
license = "MIT OR Apache-2.0"
authors = ["Fluence Labs"]
edition = "2021"
keywords = ["fluence", "web3", "wasm"]

[lib]
## lib is necessary for integration tests
## cdylib is necessary for Wasm build
crate-type = ["cdylib", "lib"]

[dependencies]
fil_actors_runtime = { workspace = true }
frc42_dispatch = { workspace = true }
fvm_shared = { workspace = true }
fvm_ipld_hamt = { workspace = true }
serde = { workspace = true }
num-traits = { workspace = true }
num-derive = { workspace = true }
cid = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
fvm_ipld_blockstore = { workspace = true }
fvm_ipld_encoding = { workspace = true }
fluence-actor-sdk = { workspace = true }

[features]
fil-actor = ["fil_actors_runtime/fil-actor"]
