networks:
  # Network created externally so individual containers can be destroyed without the network being removed.
  ipc:
    external: true
    name: ${IPC_NETWORK}

# See https://docs.docker.com/compose/extends/ for reusing and overriding definitions.

services:

  # IPC Agent daemon service
  agent:
    image: ipc-agent:${IPC_VERSION}
    container_name: ipc-agent-${IPC_AGENT_NR}
    hostname: agent-${IPC_AGENT_NR}
    ports:
      # JSON-RPC port where the ipc-agent binary on the host can issue commands.
      - 303${IPC_AGENT_NR}:3030
    volumes:
      # Configuration file gets refreshed as new subnets are created.
      - $PWD/config.toml:/root/.ipc-agent/config.toml
    networks:
      - ipc
    environment:
      HOME: /root
    env_file:
      - .env
    command:
      - --config-path
      - /root/.ipc-agent/config.toml
      - daemon
