[package]
name = "fendermint_actor_blobs"
description = "Actor for blob management"
license.workspace = true
edition.workspace = true
authors.workspace = true
version = "0.1.0"

[lib]
## lib is necessary for integration tests
## cdylib is necessary for Wasm build
crate-type = ["cdylib", "lib"]

[dependencies]
anyhow = { workspace = true }
cid = { workspace = true, default-features = false }
multihash = { workspace = true, default-features = false, features = ["blake3"] }
num-derive = { workspace = true }
num-traits = { workspace = true }
fil_actors_runtime = { workspace = true }
frc42_dispatch = { workspace = true }
fvm_ipld_encoding = { workspace = true }
fvm_ipld_blockstore = { workspace = true }
fvm_shared = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_tuple = { workspace = true }

[dev-dependencies]
fil_actors_evm_shared = { workspace = true }
fil_actors_runtime = { workspace = true, features = [
    "test_utils",
] }
hex-literal = { workspace = true }
rand = { workspace = true }

[features]
fil-actor = ["fil_actors_runtime/fil-actor"]
