# smoke-test infrastructure:
# cargo install cargo-make
#
# cd fendermint/testing/smoke-test
# - then -
# cargo make --profile ci
# - or -
# cargo make setup
# cargo make test
# docker logs smoke-ethapi
# cargo make teardown

extend = [
    { path = "../../../infra/fendermint/scripts/docker.toml" },
    { path = "../../../infra/fendermint/scripts/cometbft.toml" },
    { path = "../../../infra/fendermint/scripts/ethapi.toml" },
    { path = "../../../infra/fendermint/scripts/fendermint.toml" },
    { path = "../../../infra/fendermint/scripts/promtail.toml" },
    { path = "../../../infra/fendermint/scripts/iroh.toml" },
    { path = "./fendermint.toml" },
]

[env]
CMT_P2P_HOST_PORT = { script = ["${ROOT_SCRIPTS_DIR}/get_port.sh 30000"], condition = { env_not_set = [
    "CMT_P2P_HOST_PORT",
] } }
CMT_RPC_HOST_PORT = { script = ["${ROOT_SCRIPTS_DIR}/get_port.sh $((CMT_P2P_HOST_PORT+1))"], condition = { env_not_set = [
    "CMT_RPC_HOST_PORT",
] } }
ETHAPI_HOST_PORT = { script = ["${ROOT_SCRIPTS_DIR}/get_port.sh $((CMT_RPC_HOST_PORT+1))"], condition = { env_not_set = [
    "ETHAPI_HOST_PORT",
] } }
FENDERMINT_METRICS_HOST_PORT = { script = ["${ROOT_SCRIPTS_DIR}/get_port.sh $((ETHAPI_HOST_PORT+1))"], condition = { env_not_set = [
    "FENDERMINT_METRICS_HOST_PORT",
] } }
IROH_RPC_HOST_PORT = { script = ["${ROOT_SCRIPTS_DIR}/get_port.sh $((FENDERMINT_METRICS_HOST_PORT+1))"], condition = { env_not_set = [
    "IROH_RPC_HOST_PORT",
] } }
IROH_METRICS_HOST_PORT = { script = ["${ROOT_SCRIPTS_DIR}/get_port.sh $((IROH_RPC_HOST_PORT+1))"], condition = { env_not_set = [
    "IROH_METRICS_HOST_PORT",
] } }
TENDERMINT_RPC_URL = "http://127.0.0.1:${CMT_RPC_HOST_PORT}"
FM_ETH__LISTEN__PORT = "${ETHAPI_HOST_PORT}"

# Define the following in test specific `Makefile.toml` files,
# where `env.env` defines `NETWORK_NAME` and `TEST_DIR`, expected by `common.env`:
# env_files = [
#   { path = "./env.env" },
#   { path = "../Makefile/common.env" },
#   { path = "../Makefile/ci.env", profile = "ci" },
# ]

[tasks.default]
clear = true
run_task = { name = [
    "echo-ports",
    "setup",
    "test",
], fork = true, cleanup_task = "teardown" }

# Waiting before starting the Eth API for the CometBFT websocket to start listening.
[tasks.setup]
dependencies = [
    "create-log-volume",
    "test-data-dir",
    "test-data-env",
    "test-node-dir",
    "docker-network-create",
    "cometbft-init",
    "fendermint-init",
    "iroh-start",
    "iroh-wait",
    "fendermint-start",
    "cometbft-start",
    "cometbft-wait",
    "ethapi-start",
    "promtail-start",
    "fendermint-logs",
    "cometbft-logs",
    "ethapi-logs",
]

[tasks.echo-ports]
script = """
echo "CMT_P2P_HOST_PORT: $CMT_P2P_HOST_PORT"
echo "CMT_RPC_HOST_PORT: $CMT_RPC_HOST_PORT"
echo "ETHAPI_HOST_PORT: $ETHAPI_HOST_PORT"
echo "FENDERMINT_METRICS_HOST_PORT: $FENDERMINT_METRICS_HOST_PORT"
echo "IROH_RPC_HOST_PORT: $IROH_RPC_HOST_PORT"
echo "IROH_METRICS_HOST_PORT: $IROH_METRICS_HOST_PORT"
echo "TENDERMINT_RPC_URL: $TENDERMINT_RPC_URL"
echo "FM_ETH__LISTEN__PORT: $FM_ETH__LISTEN__PORT"
"""

[tasks.test]
dependencies = []

[tasks.teardown]
# `dependencies` doesn't seem to work with `cleanup_task`.
run_task = { name = [
    "cometbft-destroy",
    "fendermint-destroy",
    "ethapi-destroy",
    "iroh-destroy",
    "promtail-destroy",
    "docker-network-rm",
    "test-data-dir-rm",
    "destroy-log-volume",
] }

[tasks.test-data-dir]
script = """
mkdir -p ${TEST_DATA_DIR}/keys;
cp -r ${TEST_SCRIPTS_DIR} ${TEST_DATA_DIR}/scripts
"""

[tasks.test-data-dir-rm]
script = """
rm -rf ${TEST_DATA_DIR}
"""

[tasks.test-data-env]
script = """
touch ${TEST_DATA_DIR}/.env
"""

[tasks.test-node-dir]
script = """
mkdir -p ${TEST_DATA_DIR}/${NODE_NAME}/fendermint/data/logs;
mkdir -p ${TEST_DATA_DIR}/${NODE_NAME}/cometbft;
mkdir -p ${TEST_DATA_DIR}/${NODE_NAME}/iroh;
"""

[tasks.test-node-dir-rm]
script = """
rm -rf ${TEST_DATA_DIR}/${NODE_NAME}
"""
