name: Demos

on:
  workflow_call:

env:
  FOUNDRY_PROFILE: ci

jobs:
  examples-axelar-token:
    name: "Demos: Axelar token"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    defaults:
      run:
        working-directory: ./demos/axelar-token
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: pnpm/action-setup@v2
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'pnpm'
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: pnpm install
        run: |
          pnpm install
      - name: Run Forge build
        id: build
        run: |
          forge --version
          forge build --sizes
      - name: Run Forge tests
        id: test
        run: |
          forge test -vvvv
