name: Deploy to calibration net on a dedicated server

on:
  workflow_dispatch:
  pull_request:

jobs:
  deploy_to_dedicated_host:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Copy deployment script files to the host
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEDICATED_SERVER_IP_ADDRESS }}
          username: ubuntu
          key: ${{ secrets.DEDICATED_SERVER_PRIVATE_KEY }}
          source: "scripts/remote_deployment/deploy.sh"
          target: "/home/ubuntu"
      # TODO(jie): For wallet addresses, we should read from github secrets, generate a file, then copy it over
      # Ideally we shouldn't checkin evm_keystore.json into the repo.
      - name: Copy config files to the host
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEDICATED_SERVER_IP_ADDRESS }}
          username: ubuntu
          key: ${{ secrets.DEDICATED_SERVER_PRIVATE_KEY }}
          source: "scripts/remote_deployment/.ipc"
          target: "/home/ubuntu"
      - name: Set up ipc config folder on the host
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEDICATED_SERVER_IP_ADDRESS }}
          username: ubuntu
          key: ${{ secrets.DEDICATED_SERVER_PRIVATE_KEY }}
          script: rm -rf /home/ubuntu/.ipc && cp -r /home/ubuntu/scripts/remote_deployment/.ipc /home/ubuntu/
      - name: Create wallet file locally
        run: echo "${{ secrets.CI_TEST_WALLET_JSON }}" > /tmp/evm_keystore.json
      - name: Copy wallet file to the host
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEDICATED_SERVER_IP_ADDRESS }}
          username: ubuntu
          key: ${{ secrets.DEDICATED_SERVER_PRIVATE_KEY }}
          source: "/tmp/evm_keystore.json"
          target: "/home/ubuntu/.ipc/"
      - name: Run deploy scripts on the host
        uses: appleboy/ssh-action@v1.0.3
        timeout-minutes: 45
        with:
          host: ${{ secrets.DEDICATED_SERVER_IP_ADDRESS }}
          username: ubuntu
          key: ${{ secrets.DEDICATED_SERVER_PRIVATE_KEY }}
          script: bash -il /home/ubuntu/scripts/remote_deployment/deploy.sh ${{ github.head_ref }}
