name: Deploy to calibration net on a dedicated server

on:
  workflow_dispatch:
  pull_request:

jobs:
  deploy_to_dedicated_host:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
      - name: Run a command
        run: pwd
      - name: Run a command
        run: ls
      - name: Run a command
        run: ls /home/runner/work/ipc/ipc/scripts/remote_deployment/deploy.sh
      - name: Copy deployment script and config files to host
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEDICATED_SERVER_IP_ADDRESS }}
          username: ubuntu
          key: ${{ secrets.DEDICATED_SERVER_PRIVATE_KEY }}
          source: "/home/runner/work/ipc/ipc/scripts/remote_deployment/deploy.sh"
          target: "/home/ubuntu"
      - name: Checkout code repo in the host
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEDICATED_SERVER_IP_ADDRESS }}
          username: ubuntu
          key: ${{ secrets.DEDICATED_SERVER_PRIVATE_KEY }}
          script: bash /home/ubuntu/deploy.sh ${{ github.sha }}