name: Deploy to calibration net on a dedicated server

on:
  workflow_dispatch:

concurrency:
  # Only allow one run at a time for this workflow
  group: deploy-to-dedicated-host
  cancel-in-progress: true

jobs:
  deploy_to_dedicated_host:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Copy deployment script to the host
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEDICATED_SERVER_IP_ADDRESS }}
          username: textile
          key: ${{ secrets.DEDICATED_SERVER_PRIVATE_KEY }}
          source: "scripts/deploy_subnet_under_calibration_net/deploy.sh"
          target: "/home/textile"
      - name: Create wallet file locally
        run: |
          echo '${{ secrets.CI_TEST_WALLET_JSON }}' > evm_keystore.json
      - name: Copy wallet file to the host
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEDICATED_SERVER_IP_ADDRESS }}
          username: textile
          key: ${{ secrets.DEDICATED_SERVER_PRIVATE_KEY }}
          source: "evm_keystore.json"
          target: "/home/textile"
      - name: Run deploy scripts on the host
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEDICATED_SERVER_IP_ADDRESS }}
          username: textile
          key: ${{ secrets.DEDICATED_SERVER_PRIVATE_KEY }}
          script: PARENT_GATEWAY_ADDRESS=${{ secrets.PARENT_GATEWAY_ADDRESS }} PARENT_REGISTRY_ADDRESS=${{ secrets.PARENT_REGISTRY_ADDRESS }} PARENT_HTTP_AUTH_TOKEN=${{ secrets.PARENT_HTTP_AUTH_TOKEN }} bash -il /home/textile/scripts/deploy_subnet_under_calibration_net/deploy.sh ${{ github.ref_name }}
          command_timeout: 120m
