name: Tests

# This workflow is triggered from the main CI workflow.
on:
  workflow_call:

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          targets: wasm32-unknown-unknown
          toolchain: nightly
          components: rustfmt

      - name: Check code formatting
        run: cd fvm-utils && make check-fmt

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    needs: fmt
    steps:
      - uses: actions/checkout@v3

      - name: Install Tools
        uses: ./.github/actions/install-tools
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          rust: stable

      - run: cd fvm-utils && make test


  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    needs: fmt
    steps:
      - uses: actions/checkout@v3

      - name: Install Tools
        uses: ./.github/actions/install-tools
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          rust: stable

      - name: Check clippy
        run: cd fvm-utils && make check-clippy
