name: "Commonmark/Markdown: Lint"

# This workflow is triggered from the main CI workflow.
on:
  workflow_call:

jobs:
  lint-commonmark:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the project
      uses: actions/checkout@v4

    - name: Lint all commonmark/markdown files
      uses: DavidAnson/markdownlint-cli2-action@v19
      with:
        fix: false
        globs: '**/README.md;contracts/specs/**/*.md;specs/**/*.md;docs/**/*.md'
        separator: ';'